import Head from "next/head";
import MainLayout from "@/layouts/mainLayout";

import CardList from "@/components/cardList";

import { useRouter } from "next/router";
import { useState, useEffect } from "react";

export default function searchResults() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div>
          <p>{category}</p>
          <CardList data={eventi} />
        </div>
      </MainLayout>
    </>
  );
}
