import Head from "next/head";
import Image from "next/image";
import { FiCalendar, FiClock, FiMapPin } from "react-icons/fi";

import styles from "@/styles/pages/Event.module.scss";

import { useRouter } from "next/router";

// main layout
import MainLayout from "@/layouts/mainLayout";
import CtaButton from "@/components/ctaButton";

// dati fetch
import { useContext } from "react";
import { DataContext } from "@/store/DataContext";

export default function EventDetails() {
  // routing pagina dinamica
  const items = useContext(DataContext);
  const router = useRouter();
  const { id } = router.query;

  const event = items._embedded?.events.find((show) => show.id === id);

  function deleteSeconds(time) {
    let timeArray = time.split(":");
    let newTime = timeArray[0] + ":" + timeArray[1];
    return newTime;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <MainLayout>
          <div className={styles.imageContainer}>
            <Image
              className={styles.image}
              src={
                event.images[5].width === 2426 ||
                event.images[5].width === 2048 ||
                event.images[5].width === 1024 ||
                event.images[5].width === 1576
                  ? event.images[5].url
                  : event.images[2].url
              }
              alt={event.name}
              width={1920}
              height={550}
              layout="responsive"
            />
            <div className={styles.cover}>
              <div className={styles.overlay}></div>
              <h2 className={styles.title}>{event.name}</h2>
            </div>
          </div>
          {console.log(items)}
          <div className={styles.info}>
            <ul>
              <li>
                <FiCalendar />
                <p>
                  {event.dates.start.localDate.split("-").reverse().join("-")}
                </p>
              </li>
              <li>
                <FiClock />
                <p>{deleteSeconds(event.dates.start.localTime)}</p>
              </li>
              <li>
                <FiMapPin />
                <p>
                  {event._embedded.venues[0].name} -{" "}
                  {event._embedded.venues[0].city.name}
                </p>
              </li>
            </ul>
            <div className={styles.description}>
              <h3>Descrizione</h3>
              <p>
                {`Non perdere l'opportunità di assistere all'evento ${
                  event.name
                },
                in programma il ${event.dates.start.localDate
                  .split("-")
                  .reverse()
                  .join("-")} presso ${
                  event._embedded.venues[0].name
                } alle ${deleteSeconds(
                  event.dates.start.localTime
                )}. Preparati a vivere un'esperienza
                unica nel suo genere, con un artista di fama internazionale.
                Acquista subito i tuoi biglietti e non rimarrai deluso!`}
              </p>
            </div>
            <CtaButton text={"COMPRA IL BIGLIETTO"} />
          </div>
        </MainLayout>
      </main>
    </>
  );
}
