import MainLayout from "@/layouts/mainLayout";
import styles from "@/styles/pages/About.module.scss";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import { AiFillGithub } from "react-icons/ai";
import {AiFillLinkedin } from "react-icons/ai"



export default function About () { 
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <MainLayout>
    <div className={styles.About}>
     <h1 className={styles.About}>About</h1>
      <div className={styles.aboutContainer}>
        <div className={styles.profile}>
         <Image className={styles.profileImg}
           src='' 
           className={styles.profileImg} 
           alt=""
           width={350}
           height={500}
          />
         <div className={styles.profileText}>
         <h1>Marilena Messina</h1>
         <p>
          Front-end developer
         </p>

         <div className={styles.socialIcons}>
          <h3>
           <Link href="https://github.com/MariMessi"
            aria-label="GitHub"
            target="_blank"
            rel="noopener noreferrer"
            ><p><AiFillGithub/> Github</p>
            <i className="fa-brands fa-github"></i>
           </Link>
          </h3>
          <h3>
            <Link href="https://www.linkedin.com/in/marilena-messina-1914b124a/"
            aria-label="LinkedIn"
            target="_blank"
            rel="noopener noreferrer"
            ><p> <AiFillLinkedin /> Linkedin</p>
            <i className="linkedin"></i>
           </Link>
         </h3>
        </div>
      </div>
        </div>
        <div className={styles.profile}>
         <Image className={styles.profileImg}
           src=''  
           alt=""
           width={350}
           height={500}
          />
         <div className={styles.profileText}>
         <h1>Stefania Rapisarda</h1>
         <p>
          Front-end developer
         </p>

         <div className={styles.socialIcons}>
          <h3>
           <Link href="https://github.com/stefRapis"
            aria-label="GitHub"
            target="_blank"
            rel="noopener noreferrer"
            ><p><AiFillGithub/> Github</p>
            <i className="fa-brands fa-github"></i>
           </Link>
          </h3>
          <h3>
            <Link href="https://www.linkedin.com/in/stefaniarapisarda/"
            aria-label="LinkedIn"
            target="_blank"
            rel="noopener noreferrer"
            ><p> <AiFillLinkedin /> Linkedin</p>
            <i className="linkedin"></i>
           </Link>
         </h3>
        </div>
      </div>
       </div>
       <div className={styles.profile}>
         <Image className={styles.profileImg}
           src='' 
           alt=""
           width={350}
           height={500}
          />
         <div className={styles.profileText}>
         <h1>Flavia Pinello</h1>
         <p>
          Front-end developer
         </p>

         <div className={styles.socialIcons}>
          <h3>
           <Link href="https://github.com/FlaviaPinello"
            aria-label="GitHub"
            target="_blank"
            rel="noopener noreferrer"
            ><p><AiFillGithub/> Github</p>
            <i className="fa-brands fa-github"></i>
           </Link>
          </h3>
          <h3>
            <Link href="https://www.linkedin.com/in/flavia-pinello-a456b697/"
            aria-label="LinkedIn"
            target="_blank"
            rel="noopener noreferrer"
            ><p> <AiFillLinkedin /> Linkedin</p>
            <i className="linkedin"></i>
           </Link>
         </h3>
        </div>
      </div>
       </div>
       <div className={styles.profile}>
         <Image className={styles.profileImg}
           src=''  
           alt=""
           width={350}
           height={500}
          />
         <div className={styles.profileText}>
         <h1>Fabio Farinella</h1>
         <p>
          Front-end developer
         </p>

         <div className={styles.socialIcons}>
          <h3>
           <Link href="https://github.com/FabioFarinella96"
            aria-label="GitHub"
            target="_blank"
            rel="noopener noreferrer"
            ><p><AiFillGithub/> Github</p>
            <i className="fa-brands fa-github"></i>
           </Link>
          </h3>
          <h3>
            <Link href="https://www.linkedin.com/in/fabio-farinella/"
            aria-label="LinkedIn"
            target="_blank"
            rel="noopener noreferrer"
            ><p> <AiFillLinkedin /> Linkedin</p>
            <i className="linkedin"></i>
           </Link>
         </h3>
        </div>
      </div>
       </div>
       <div className={styles.profile}>
         <Image className={styles.profileImg}
           src=''  
           alt=""
           width={350}
           height={500}
          />
         <div className={styles.profileText}>
         <h1>Greta Tomasoni</h1>
         <p>
          Front-end developer
         </p>

         <div className={styles.socialIcons}>
          <h3>
           <Link href="https://github.com/gretaTomasoni"
            aria-label="GitHub"
            target="_blank"
            rel="noopener noreferrer"
            ><p><AiFillGithub/> Github</p>
            <i className="fa-brands fa-github"></i>
           </Link>
          </h3>
          <h3>
            <Link href="https://it.linkedin.com/in/greta-tomasoni-07a258198"
            aria-label="LinkedIn"
            target="_blank"
            rel="noopener noreferrer"
            ><p> <AiFillLinkedin /> Linkedin</p>
            <i className="linkedin"></i>
           </Link>
         </h3>
        </div>
      </div>
       </div>  
      </div>
    </div>
   </MainLayout>
   </>
    
  );
};

