import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "@/styles/pages/Cart.module.scss";

// main layout
import MainLayout from "@/layouts/mainLayout";

// components
import CartList from "@/components/cartList";
import SecondaryButton from "@/components/SecondaryButton";

export default function Cart() {
  const [cartContext, setCartContext] = useState([]);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const data = JSON.parse(localStorage.getItem("event")) || [];
      setCartContext(data);
    }
  }, []);

  const [priceCheckout, setPriceCheckout] = useState(0);

  useEffect(() => {
    setPriceCheckout(
      cartContext.reduce((acc, data) => acc + data.price * data.qty, 0)
    );
  }, [cartContext]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <div className={styles.Cart}>
            <h3 className={styles.title}>Carrello:</h3>
            <CartList
              cartContext={cartContext}
              setCartContext={setCartContext}
              priceCheckout={priceCheckout}
              setPriceCheckout={setPriceCheckout}
            />
            <hr className={styles.line} />
            <div className={styles.checkout}>
              <p>Totale: {priceCheckout}€</p>
              <SecondaryButton text={"CHECKOUT"} />
            </div>
          </div>
        </MainLayout>
      </main>
    </>
  );
}
