import Head from "next/head";
import MainLayout from "@/layouts/mainLayout";
import styles from "@/styles/pages/Events.module.scss";
// import eventsList from "@/mock/events";

import CardList from "@/components/cardList";

import { useContext } from "react";
import { DataContext } from "@/store/DataContext";

export default function Events() {
  const items = useContext(DataContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className={styles.Events}>
          <p>Scopri gli eventi</p>
          <CardList data={items.state.fetchedData} />
        </div>
      </MainLayout>
    </>
  );
}
