/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 prov.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/prov.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Joint} />
      <primitive object={nodes.body} />
      <primitive object={nodes.eye_L} />
      <primitive object={nodes.eye_R} />
      <primitive object={nodes.eyelash_L} />
      <primitive object={nodes.eyelash_R} />
      <primitive object={nodes.tooth} />
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Fur_Fox_FRONT_2944} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.Fur_Fox_FRONT_2944} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.Cloth_mesh_16.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.Cloth_mesh_17.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.Cloth_mesh_18.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.Cloth_mesh_19.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.Cloth_mesh_20.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes._mesh.geometry} material={materials.Material288819} position={[0.08, 1.12, 0.07]} rotation={[1.97, 0.43, -0.38]} />
      <mesh geometry={nodes._mesh_1.geometry} material={materials.Material288819} position={[0.07, 1.07, 0.07]} rotation={[1.48, -0.26, -0.26]} />
      <mesh geometry={nodes._mesh_2.geometry} material={materials.Material288819} position={[0.06, 1.03, 0.07]} rotation={[1.71, 0.14, -0.19]} />
      <mesh geometry={nodes._mesh_3.geometry} material={materials.Material288819} position={[-0.05, 1.54, 0.01]} rotation={[1.7, 0.46, 0.39]} />
      <mesh geometry={nodes._mesh_4.geometry} material={materials.Material288819} position={[-0.03, 1.47, 0.04]} rotation={[1.19, 0.36, -0.25]} />
      <mesh geometry={nodes._mesh_5.geometry} material={materials.Material288819} position={[0, 1.41, 0.07]} rotation={[0.93, 0.22, -0.11]} />
      <mesh geometry={nodes._mesh_6.geometry} material={materials.Material288819} position={[0, 1.34, 0.08]} rotation={[1.65, -0.16, -0.35]} />
      <mesh geometry={nodes._mesh_7.geometry} material={materials.Material288819} position={[-0.01, 1.26, 0.08]} rotation={[1.55, 0, 0.44]} />
      <mesh geometry={nodes._mesh_8.geometry} material={materials.Material288819} position={[-0.01, 1.19, 0.08]} rotation={[1.69, 0.08, -0.21]} />
    </group>
  )
}

useGLTF.preload('/prov.glb')
