/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 prov2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/prov2.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Joint} />
      <primitive object={nodes.body} />
      <primitive object={nodes.eye_L} />
      <primitive object={nodes.eye_R} />
      <primitive object={nodes.eyelash_L} />
      <primitive object={nodes.eyelash_R} />
      <primitive object={nodes.tooth} />
      <directionalLight intensity={1} decay={2} color="#969696" position={[1.5, 3, 1.5]} rotation={[-1.11, 0.42, 0]} />
      <mesh geometry={nodes.MatShape_72670_Node.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.MatShape_72673_Node.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.MatShape_72676_Node.geometry} material={materials.PT_FABRIC_FRONT_3019} />
      <mesh geometry={nodes.MatShape_72714_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_72717_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_72720_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_72723_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_72726_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_72729_Node.geometry} material={materials.PT_FABRIC_FRONT_2999} />
      <mesh geometry={nodes.MatShape_13586_Node.geometry} material={materials.Material288819} position={[0.08, 1.12, 0.07]} rotation={[1.97, 0.43, -0.38]} />
      <mesh geometry={nodes.MatShape_13594_Node.geometry} material={materials.Material288819} position={[0.07, 1.07, 0.07]} rotation={[1.48, -0.26, -0.26]} />
      <mesh geometry={nodes.MatShape_13602_Node.geometry} material={materials.Material288819} position={[0.06, 1.03, 0.07]} rotation={[1.71, 0.14, -0.19]} />
      <mesh geometry={nodes.MatShape_16802_Node.geometry} material={materials.Material288819} position={[-0.05, 1.54, 0.01]} rotation={[1.7, 0.46, 0.39]} />
      <mesh geometry={nodes.MatShape_16810_Node.geometry} material={materials.Material288819} position={[-0.03, 1.47, 0.04]} rotation={[1.19, 0.36, -0.25]} />
      <mesh geometry={nodes.MatShape_16818_Node.geometry} material={materials.Material288819} position={[0, 1.41, 0.07]} rotation={[0.93, 0.22, -0.11]} />
      <mesh geometry={nodes.MatShape_16826_Node.geometry} material={materials.Material288819} position={[0, 1.34, 0.08]} rotation={[1.65, -0.16, -0.35]} />
      <mesh geometry={nodes.MatShape_16834_Node.geometry} material={materials.Material288819} position={[-0.01, 1.26, 0.08]} rotation={[1.55, 0, 0.44]} />
      <mesh geometry={nodes.MatShape_16842_Node.geometry} material={materials.Material288819} position={[-0.01, 1.19, 0.08]} rotation={[1.69, 0.08, -0.21]} />
      <mesh geometry={nodes['袖*2'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['袖*2_1'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['袖*2_2'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['袖*3'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['袖*3_1'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['袖*3_2'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_938287.geometry} material={materials.Fur_Fox_FRONT_2944} />
      <mesh geometry={nodes.Pattern2D_938287_1.geometry} material={materials.Fur_Fox_BACK_2944} />
      <mesh geometry={nodes.Pattern2D_938287_2.geometry} material={materials.Fur_Fox_SIDE_2944} />
      <mesh geometry={nodes.Pattern2D_938288.geometry} material={materials.Fur_Fox_FRONT_2944} />
      <mesh geometry={nodes.Pattern2D_938288_1.geometry} material={materials.Fur_Fox_BACK_2944} />
      <mesh geometry={nodes.Pattern2D_938288_2.geometry} material={materials.Fur_Fox_SIDE_2944} />
      <mesh geometry={nodes['前上-1'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['前上-1_1'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['前上-1_2'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['前幅-1'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['前幅-1_1'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['前幅-1_2'].geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551242.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551242_1.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551242_2.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551243.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551243_1.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes.Pattern2D_551243_2.geometry} material={materials['Cotton_Outer_Woven_DSS-18_FRONT_2951']} />
      <mesh geometry={nodes['后幅*6'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['后幅*6_1'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['后幅*6_2'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['后幅*3'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['后幅*3_1'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes['后幅*3_2'].geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926147.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926147_1.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926147_2.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926148.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926148_1.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
      <mesh geometry={nodes.Pattern2D_926148_2.geometry} material={materials['PD-00400828_medium_FRONT_2962']} />
    </group>
  )
}

useGLTF.preload('/prov2.glb')
